---

- name: Create yum repository
  yum_repository:
    name: vscode
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Install Visual Studio Code
  dnf:
    name: code
    state: present
  become: yes

- name: Get installed Visual Studio Code extensions
  command: code --list-extensions
  register: vscode_extenstions_installed
  changed_when: no

- name: Install Visual Studio Code extensions
  shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  register: vscode_install_extension
  when: item not in vscode_extenstions_installed.stdout
  changed_when:
    - "'is already installed' not in vscode_install_extension.stdout"
    - "'was successfully installed' in vscode_install_extension.stdout"
